# Usa a imagem oficial do PHP 8.4 com FPM, que é otimizada para produção.
FROM php:8.4-fpm

# Define o diretório de trabalho dentro do contêiner.
WORKDIR /var/www

# Instala as dependências do sistema necessárias para as extensões do PHP e outras ferramentas.
# - libpq-dev: para a conexão com o PostgreSQL.
# - libzip-dev: para manipulação de arquivos .zip.
# - Outras: para processamento de imagens, git, etc.
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    unzip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    git \
    curl \
    libpq-dev \
    libzip-dev \
    libonig-dev \
    libxml2-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Instala as extensões do PHP necessárias para o Laravel.
# pdo_pgsql e pgsql: para o PostgreSQL.
# gd: para manipulação de imagens.
# bcmath: para matemática de precisão.
RUN docker-php-ext-install pdo_pgsql pgsql mbstring exif pcntl bcmath gd zip

# Instala o Composer (gerenciador de dependências do PHP) globalmente.
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Cria um usuário do sistema para rodar a aplicação, evitando rodar como root.
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copia o código da aplicação para dentro do contêiner.
COPY . /var/www

# Ajusta as permissões das pastas para que o Laravel e o servidor web possam escrever nelas.
COPY --chown=www:www . /var/www

# Expõe a porta 9000 para que o Nginx possa se comunicar com o PHP-FPM.
EXPOSE 9000

# Define o comando padrão para iniciar o serviço PHP-FPM.
CMD ["php-fpm"]
